explore_costmap:
  global_frame:              /map
  rolling_window:            false
  track_unknown_space:       true

  explore_boundary:
    resize_to_boundary:    true
    frontier_travel_point: closest
    
  plugins:
    - {name: explore_boundary,     type: "frontier_exploration::BoundedExploreLayer"}
    - {name: obstacles_costmap2d,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,            type: "costmap_2d::InflationLayer"}
